<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['administrators_app_description'] = 'With the Administrators app, you can grant access to specific apps to groups of users on the system.';
$lang['administrators_app_name'] = 'Administrators';
