<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['administrators_app_description'] = 'С приложением "Администраторы", вы можете предоставить доступ к конкретным приложениями группам пользователей в системе.';
$lang['administrators_app_name'] = 'Администраторы';
