<?php
// Generated by translation system
// http://www.clearfoundation.com/docs/developer/translations/

$lang['administrators_app_description'] = 'Dzięki aplikacji Administratorzy, możesz zapewnić dostęp do poszczególnych aplikacji grupom użytkowników systemowych.';
$lang['administrators_app_name'] = 'Administratorzy';
